name: lsst-discovery
channels:
  - conda-forge
  - defaults
dependencies:
  - c-compiler
  - compilers
  - cxx-compiler
  - python>=3.9
  - pip
  - aesara-theano-fallback==0.1.0
  - arviz==0.12.1
  - astropy==5.3.2
  - corner==2.2.2
  - cython==3.0.10
  - h5py==3.9.0
  - matplotlib==3.7.2
  - numpy==1.21.6
  - pandas
  - pymc3==3.11.5
  - pymc3-ext==0.1.1
  - scipy==1.7.3
  - seaborn
  - theano-pymc==1.1.2
  - xarray==2022.9.0
  - pip:
     - dynesty==2.1.3
     - emcee==3.1.6
     - notebook==6.4.13
     - setuptools
